---
- hosts: all
  become: yes
  tasks:
    - name: Install Chrony NTP
      apt:
        name: chrony
        state: present

    - name: Update NTP settings
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^pool'
        line: "pool {{ item }}"
        state: present
      with_items:
        - 2.ubuntu.pool.ntp.org
        - 3.ubuntu.pool.ntp.org

    - name: Add repository
         apt_repository:
           repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu jammy-ubuntu
           state: present

    - name: Install prerequisites
      apt:
        name: 
          - software-properties-common
          - python3-pip
          - python3-openstackclient
        state: present

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Enable MariaDB service
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        present

    - name: Install memcached
      service:
        name: memcached
        state: present

    - name: Start memcached
      service:
        name: memcached
        state: restarted

    - name: Install etcd
      apt:
        name: etcd
        state: present

    - name: Set up etcd
      copy:
        dest: /etc/default/etcd
        content: |
          ETCD_LISTEN_PEER_URLS="http://127.0.0.1:2380"
          ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379"
          ETCD_INITIAL_ADVERTISE_PEER_URLS="htp://127.0.0.1:2380"
          ETCD_INITIAL_CLUSTER="controller=http://127.0.0.1:2380"
          ETCD_INITIAL_CLUSTER_TOKEN="etcd_cluster_token"
          ETCD_INITIAL_CLUSTER_STATE="new"
          ETCD_ADVERTISE_CLIENT_URLS="http://127.0.0.1:2379"


    - name: Restart etcd service
      service:
        name: etcd
        state: restarted
        enabled: yes




